### PR TITLE
Add a pop up dialog box for Polls/Survey done ! #1765 🌟🌟🌟

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #1765
Add a pop up dialog box for Polls/Survey done properly -

https://github.com/user-attachments/assets/34064329-7c69-401e-a4cc-64f07b3a4d1e

Screenshot 2024-10-30 043451
Screenshot 2024-10-30 043519

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal please merge my PR with level 3

I have added this new feature correctly (if you vote once, you won't see it again after reload..)..

🟠Adding Polls/Survey related to your website, content or products can offer several benefits:

⚪Polls/Survey encourage user interaction, making visitors feel more involved with your site.
⚪They provide direct feedback on user preferences, helping you understand your audience better.
⚪Polls/Survey results can guide future content creation or product development based on what your audience cares about.

Thank You

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 One popup was enough .... Anybody would get irritated on getting two pop-up ... You can add it in side like the cookie policy

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 One popup was enough .... Anybody would get irritated on getting two pop-up ... You can add it in side like the cookie policy

@PriyaGhosal Users will not have any problem for this, because if you vote once, you won't see it again after reload.. its a nice feature..

And it's better to have it as a popup, then no one will ignore it which will make it easier for you to collect votes from all users..

I have done this before on some website they also suggested this and add level 3..

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal please merge my PR with level 3

Thank You

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal please merge my PR with level 3

Thank You

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 BuddyTrail has one popup already... Two pop is something not desirable

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 BuddyTrail has one popup already... Two pop is something not desirable

@PriyaGhosal I have done this same thing on some other website they also have two popup one newsletter and one for survey... that's why i add this as a popup.. And it's better to have it as a popup, then no one will ignore it which will make it easier for you to collect votes from all users..

you said "Two pop is something not desirable" but i don't think because its survey, it's better to have it as a popup, then no one will ignore it which will make it easier for you to collect votes from all users... if you vote once, you won't see it again after reload.. 

@PriyaGhosal please understand and merge my PR with label

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal & something is wrong with your newsletter popup because it shows up again after subscribing.. which doesn't good

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal ?

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 Please see the conflicts .

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Please see the conflicts .

@PriyaGhosal done

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal please merge my PR otherwise i can't able to do another task

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal please merge my PR with Level 3,otherwise i can't able to do another task

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Please see the conflicts .

???

**Comment by Subhajit-2023-44** [comment]
> @PriyaGhosal & something is wrong in your newsletter popup because it shows up again after sign up.. which doesn't good
> 
> That's why you maybe think Two pop is something not desirable

@PriyaGhosal ??

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Please see the conflicts .

@PriyaGhosal You said solve conflicts, i solve conflicts and wait 5 days, and now why you closed my pr ? 😭😭

image

Please merge my PR

**Pull request closed without merging**
