### PR TITLE
Changed the Cursor Animation to INDIAN TRICOLOR Theme and ADDED IT TO ALL WEBPAGES (which were without cursor Effect)

### PR DESCRIPTION
**Pull request by PatelHarsh2006**
Changed the Cursor Animation to INDIAN TRICOLOR Theme and ADDED IT TO ALL WEBPAGES (Which were Without Cursor Animation Effect)

   (BEFORE):
https://github.com/user-attachments/assets/12328a71-d6d7-4714-8c88-fc2e2a493be0

ALSO, So Many Pages were Without Cursor Animation Effect, So also Added Cursor Animation Effect to All Such Pages :
Some of Them Are :

     AFTER:
https://github.com/user-attachments/assets/9d542abf-de82-40ad-9d7e-b7dca099aae6

   High Quality Video:
https://github.com/user-attachments/assets/a52c57ae-fc1a-4fe5-8a6e-97e34a18f080

<br>
Mam, Please Don't Close the Pull Request if it Shows RESOLVE CONFLICTS, Instead Reply ME in Such Case and Give Me Few Hours of Time in case I haven't Seen it, for Resolving Conflicts, and I will Reply Back when resolved conflicts and then Merge it, but Please don't close it. ( Bcz we just have to remove <<<<<  and ------ kind of tags that github by errors takes in the commited file, so i will remove it, if it happens !)

<br><br><br>

# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.)

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Please Review My Changes and Merge it by Assigning Labels to It !!!
( Mam, Please Don't Close the Pull Request if it Shows RESOLVE CONFLICTS, Instead Reply ME in Such Case and Give Me Few Hours of Time in case I haven't Seen it, for Resolving Conflicts, and I will Reply Back when resolved conflicts and then Merge it, but Please don't close it. )

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 Please see the conflicts . Resolve the conflicts .

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Conflicts are Resolved ! Thank You Mam, for Your Patience !

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 Please see the conflicts .

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Conflicts are Resolved !!!

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Mam, Can You Please Guide me on how can I Correct these Deployment failed Issue that has occured in this Pull Request

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Conflicts have been Resolved ( Sorry Mam, for the Inconvinence, Because so many files were changed so it happening that that shows me 3-4 files Resolve Conflicts when I do it and You try to Again Merge it again shows me another 4-5 files for resolving Conflicts and not all at a time but once all file will get conflicts resolved you will be able to merge so please keep trying to merge so that it keep showing me resolve conflicts, Otherwise it keeps showing me no conflicts in merging the file, Hope you Understand the Problem and try to cooperate with it )

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 Please look into conflicts 
image

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal  Finally Mam, the Conflicts are resolved

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Please merge it by Assigning Labels to it !

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 
image

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Conflicts have been Resolved
Screenshot 2024-10-28 114153

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Conflicts are resolved

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 In main page cursor is not working other pages its working

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Mam Can U Please Show Me Video what's Exactly the Problem is !

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 Cursor is not uniform as main page will have sky cursor colour and other would have tricolour cursor

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Yes this Sky Color was before(my new changes) thats why it might be showing ( while other pages were not having any effect ), as You have not merge it yet. Mam, You can See in my video ( uploaded at the time of PR (👆)) index file also have tricolor effect only.

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 In main page tricolour cursor is not showing

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 Are you working on it

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Yes Mam, I am Working on it !

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Mam, Please Check If It is Working Now or Not ?

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 no in main page tricolour cursor is not working

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 it is showing conflicts

**Comment by PatelHarsh2006** [comment]
@PriyaGhosal Conflicts have been resolved

**Comment by PriyaGhosal** [comment]
@PatelHarsh2006 
Great contribution ! 🎉 Your pull request has been successfully merged! Also Take a moment to ⭐ Star the repository if you haven't already.

**Pull request merged**
