### PR TITLE
BookNow button is finally working

### PR DESCRIPTION
**Pull request by INam1995**
https://github.com/PriyaGhosal/BuddyTrail/issues/171 issue

Fixes: https://github.com/PriyaGhosal/BuddyTrail/issues/171

Description
Hi @PriyaGhosal,
I noticed that the Book Now button under the treks in the Explore Now section wasn't functional. I've fixed the issue and made the button fully functional, allowing it to capture and process user data as well.
Please merge these changes and label it as Label . If you encounter any issues, feel free to reach out to me.

Close #1404 it and kindly merge this PR finally! as i have fixed the book now button issue 

Type of PR
[ x] Feature enhancement
Screenshots / videos (if applicable)

[ x] I have made this change from my own.
[ x] My code follows the style guidelines of this project.
[ x] I have performed a self-review of my own code.
[ x] I have commented my code, particularly in hard-to-understand areas.
[ x] I have made corresponding changes to the documentation.
[ x] My changes generate no new warnings.
[ x] I have tested the changes thoroughly before submitting this pull request.
[ x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by INam1995** [comment]
@PriyaGhosal please merge it or if there is an issue then please let me know

**Comment by PriyaGhosal** [comment]
@INam1995 Can you attach some SS.

**Comment by PriyaGhosal** [comment]
@INam1995 Please reply

**Comment by INam1995** [comment]
https://github.com/user-attachments/assets/7ed282df-e9de-4865-bafa-e9755b6d7d84

 @PriyaGhosal 
 check it now!!

**Comment by INam1995** [comment]
@PriyaGhosal kindly merge it

**Comment by PriyaGhosal** [comment]
@INam1995 Great contribution ! 🎉

**Pull request merged**
