### PR TITLE
Bug fixed: Made footer links working on "team" page

### PR DESCRIPTION
**Pull request by Palmistry2310**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #1295 

# Description

Previously footer links on team page were not working , which creates problem in navigation through pages. i have made the footer links working on team page.
fixed issue no. #1295 

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
### **before:**

https://github.com/user-attachments/assets/fe3ce55e-b8ca-4a27-817f-c8cd94a22188

### **after:**

https://github.com/user-attachments/assets/571bb522-a57e-441a-9213-b3a6b8413d7d

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

@PriyaGhosal please review the pr, assign and add necessary labels.

### CODE REVIEW

**Comment by Palmistry2310** [comment]
@PriyaGhosal please review this pr.

**Comment by PriyaGhosal** [comment]
@Palmistry2310 Please see the conflicts . Resolve the conflicts .

**Comment by Palmistry2310** [comment]
@PriyaGhosal i have resolved the conflicts now

**Comment by PriyaGhosal** [comment]
@Palmistry2310 
image
These links are not working in team section . Please make them working .

**Comment by Palmistry2310** [comment]
@PriyaGhosal I have made the changes. Please have a look at them now.

**Comment by PriyaGhosal** [comment]
@Palmistry2310 Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile!
Great contribution ! 🎉

**Pull request merged**
