### PR TITLE
Cookie popup added

### PR DESCRIPTION
**Pull request by Amulya-B28**
# Related Issue

Addition of cookie pop up along with Cookie policies.

# Description

This pop up has 3 options to customize, accept or reject cookies and also a link 'Cookie Policy' to read the policies of the website.

Issue no. : #519 

# Type of PR

- [ ] Bug fix
- [] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
image
image

# Checklist:
- [] I have made this change from my own.
- [] I have taken help from some online resources.
- [] My code follows the style guidelines of this project.
- [] I have performed a self-review of my own code.
- [] I have commented my code, particularly in hard-to-understand areas.
- [] My changes generate no new warnings.
- [] I have tested the changes thoroughly before submitting this pull request.
- [] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Amulya-B28** [comment]
Since i have added the pop up as well as the cookie policy, can i get the level 2 tag please. Thank you.

**Comment by Amulya-B28** [comment]
Can you please tell me why is it showing deploy failed on few checks and how can I rectify it.

**Comment by PriyaGhosal** [comment]
@Amulya-B28 
Due to a conflicting issue, some code was removed from the repository. We are investigating the matter. Meanwhile, please check on your end, and if your PR code no longer exists, kindly create the PR again for merging.Please Do Sync fork before then add your part in code as none of the contributions are visible in website BuddyTrail. Thank you for your understanding!

**Comment by Amulya-B28** [comment]
Okay. I'll update it by today.

**Pull request closed without merging**
