### PR TITLE
bug fixed: made header logo working on about, faq, blog, contact page

### PR DESCRIPTION
**Pull request by Palmistry2310**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #1426 

# Description

the header logo was not redirecting to the home page.  with this pr made the logo working.

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

https://github.com/user-attachments/assets/25553a53-795d-4cac-9e6b-a2b860be3eba

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

@PriyaGhosal please review this pr.

### CODE REVIEW

**Comment by Palmistry2310** [comment]
@PriyaGhosal please review this pr!

**Comment by PriyaGhosal** [comment]
@Palmistry2310 
Please see the conflicts .

**Comment by PriyaGhosal** [comment]
@Palmistry2310 
Are you working on it or should I close it

**Comment by Palmistry2310** [comment]
@PriyaGhosal have resolved conflicts now.

**Comment by PriyaGhosal** [comment]
Sorry, This issue has already been addressed  Find another issue or feature to contribute to. Thank you!

**Pull request closed without merging**
