### PR TITLE
Modify About Us Page Navbar and Add Theme Toggle 

### PR DESCRIPTION
**Pull request by AnushkaChouhan25**
# Related Issue
 
Fixes:  #1756 

# Description
Add theme toggle button functionality on about us which was not working, make consistent hover effect of buttons, slighlty modify navbar and correct about us heading text.
 

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
image
image
image

# Checklist:

- [x] I have made this change from my own. 
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code. 
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@AnushkaChouhan25 Please see the conflicts .

**Comment by AnushkaChouhan25** [comment]
@PriyaGhosal Done

**Comment by PriyaGhosal** [comment]
@AnushkaChouhan25 black navbar not looking good.  Find another issue or feature to contribute to. Thank you!

**Comment by AnushkaChouhan25** [comment]
Hey @PriyaGhosal, Can you please check my issue, it is not about changing navbar color, it is correcting about us page. 
Can you please check it once correctly , Thank you

**Comment by MastanSayyad** [comment]
@PriyaGhosal Can you look into this, may be there is some kind of mistake. review it and let @AnushkaChouhan25 know.

**Comment by PriyaGhosal** [comment]
@AnushkaChouhan25 Please resolve the conflicts .

**Comment by AnushkaChouhan25** [comment]
@PriyaGhosal 👍

**Pull request merged**
