### PR TITLE
Add a new ChatBot Assistant done ! 

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new Feature - #1246 #1248
Add a ChatBot Assistant done✅

Before - #1246 

Screenshot 2024-10-22 145105
Screenshot 2024-10-22 145051

After -

https://github.com/user-attachments/assets/d4ce87a9-8135-4d9a-8f7a-bd96023a5021

https://github.com/user-attachments/assets/8229c551-cf14-42d8-a058-cf823e56325c

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal done properly

**Comment by Subhajit-2023-44** [comment]
Done 

Screenshot 2024-10-22 152030

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile!
Great contribution ! 🎉

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 
image
Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request merged**
