### PR TITLE
Fix the Blog page 

### PR DESCRIPTION
**Pull request by KrishChothani**
Fixes:  #1683 

# Description

There is not visible proper text and also not fetch the blogs . so it create and there is also some code issue which show code in website page which fix by me 

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

# BEFORE ::
https://github.com/user-attachments/assets/7189a7c7-80ae-40de-beb7-e2da7dced01d

# AFTER :
https://github.com/user-attachments/assets/fdff113c-2e3f-42dd-b10f-33ce9de90adf

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by KrishChothani** [comment]
Action Items:

- Please review the changes made in PR #1689.
- If the review is satisfactory, kindly assign the PR for merging.
- Note that merging this PR will also resolve the issues mentioned in #1682.

**Comment by PriyaGhosal** [comment]
@KrishChothani Please see the conflicts .

**Comment by KrishChothani** [comment]
Hey @PriyaGhosal 

I resolve all conflict

please review

**Comment by KrishChothani** [comment]
and please let me know if there is any other conflict

**Comment by KrishChothani** [comment]
And please assign good level for it

**Comment by KrishChothani** [comment]
## And please can you review this PR :: #1635

**Comment by PriyaGhosal** [comment]
@KrishChothani Great contribution ! 🎉 Your pull request has been successfully merged! Also Take a moment to ⭐ Star the repository if you haven't already.

**Pull request merged**
