### PR TITLE
Contributor page redesigned

### PR DESCRIPTION
**Pull request by Son7c**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.)

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Before

https://github.com/user-attachments/assets/d32eec34-6649-4d54-bc88-0c4905b471af

After

https://github.com/user-attachments/assets/2ce80cb4-1862-40b3-9d9e-5646f915caba

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Son7c** [comment]
@PriyaGhosal Please merge this PR

**Comment by Son7c** [comment]
@anuragverma108 Please merge this PR.

**Comment by Son7c** [comment]
@PriyaGhosal Please merge this PR.

**Comment by Son7c** [comment]
@anuragverma108

**Comment by PriyaGhosal** [comment]
@Son7c This was already done before. I guess you didn't pull all the latest changes before pushing your feature/bug fixes to the main branch.

**Comment by Son7c** [comment]
@PriyaGhosal Ya my mistake sorry.

**Pull request closed without merging**
