### PR TITLE
Added README.md steps  

### PR DESCRIPTION
**Pull request by Anjalis14**

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@Anjalis14 Add this in Contributing.md .......After resolving the conflicts, please open a new PR for review.
Thank you!

**Comment by Anjalis14** [comment]
ok sure i will

**Comment by PriyaGhosal** [comment]
@Anjalis14 For Now I have merged your PR . Now You can work on Contributing.md file

**Comment by Anjalis14** [comment]
@PriyaGhosal  i have to add steps to contribute in contributing.md file right ???

**Pull request merged**
