### PR TITLE
Fixed get in touch section in home page

### PR DESCRIPTION
**Pull request by AsifQamar**
please review and merge it
Screenshot_305

### CODE REVIEW

**Comment by AsifQamar** [comment]
@PriyaGhosal please review and merge it

**Comment by PriyaGhosal** [comment]
@AsifQamar Fix these two as they got misplaced
image
image

**Comment by AsifQamar** [comment]
> @AsifQamar Fix these two as they got misplaced image image

That two was misplaced before my changes only, merge this pr I'll create a new or for them

**Comment by AsifQamar** [comment]
> @AsifQamar Fix these two as they got misplaced image image

OK I'll dot it

**Comment by AsifQamar** [comment]
> @AsifQamar Fix these two as they got misplaced image image

**Pull request closed without merging**
