### PR TITLE
Fixed whole contact page

### PR DESCRIPTION
**Pull request by AsifQamar**
@PriyaGhosal @samarth-6 please review and give it level 3

before
Screenshot_489

after
Screenshot_490
Screenshot_491

### CODE REVIEW

**Review by MastanSayyad — APPROVED** [review]

**Comment by MastanSayyad** [comment]
@AsifQamar issue link or number pls

**Comment by AsifQamar** [comment]
> @AsifQamar issue link or number pls

@MastanSayyad https://github.com/PriyaGhosal/BuddyTrail/issues/1970

**Comment by AsifQamar** [comment]
@MastanSayyad please give it in higher level

**Comment by MastanSayyad** [comment]
@AsifQamar assign issue has level 1 so I have given level 2

**Comment by AsifQamar** [comment]
> @AsifQamar assign issue has level 1 so I have given level 2

its auto assign thats why its showing level one , you can give level 3 600 lines of code is added

**Pull request merged**
