### PR TITLE
navbar consistent for about, blog, contact, team pages

### PR DESCRIPTION
**Pull request by Arkyapatwa**
# Related Issue

Navbar Consistency on all pages Issue 

Fixes: #1528 

# Description

Navbars of the various pages were different and the links alignments were also not correct.

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

image
image
image
image

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@Arkyapatwa Please see the conflicts .

**Comment by PriyaGhosal** [comment]
@Arkyapatwa Please see the conflicts . Are you working on it or should I close it

**Comment by Arkyapatwa** [comment]
Hey @PriyaGhosal , I have resolved the conflicts now you can proceed.

**Comment by PriyaGhosal** [comment]
@Arkyapatwa There are showing conflicts

**Comment by PriyaGhosal** [comment]
@Arkyapatwa So sorry for your inconvenience ..... Please resolve it now I will merge yours first only on priority basis

**Comment by Arkyapatwa** [comment]
@PriyaGhosal, Done

**Comment by PriyaGhosal** [comment]
@Arkyapatwa 
image
Please resolve

**Pull request closed without merging**
