### PR TITLE
Update F&Q.html - footer added in F&Q page

### PR DESCRIPTION
**Pull request by pc-daukiya**
# Related Issue

None

Fixes:  #1311 

# Description

The footer is now on the FAQ page. As a result, the page have a consistent footer section like the other pages.

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Before
Screenshot 2024-10-22 082913
After
Screenshot 2024-10-22 102754

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@pc-daukiya 
image
This is showing in preview.Please see the conflicts . Resolve the conflicts .

**Comment by PriyaGhosal** [comment]
@pc-daukiya Are you working on it

**Comment by pc-daukiya** [comment]
@PriyaGhosal no

**Comment by pc-daukiya** [comment]
I completed this already

**Comment by PriyaGhosal** [comment]
@pc-daukiya Please see the conflicts

**Comment by PriyaGhosal** [comment]
@pc-daukiya Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
