### PR TITLE
ADDED PRIVACY POLICY PAGE

### PR DESCRIPTION
**Pull request by snehhhcodes**
Fixes:  #1074 

# Description

Resolved the issue by creating a separate privacy policy page as requested. The footer link has been updated to redirect users to this newly created page, ensuring easy access to privacy information.

# Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[screen-capture (1).webm](https://github.com/user-attachments/assets/96ac9eef-9ac7-41e5-b66e-8dc0ce8bbee5)

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by snehhhcodes** [comment]
@PriyaGhosal please review this once and add level according to it maybe 3 as i made a separate page!!

**Comment by snehhhcodes** [comment]
@PriyaGhosal please check it once and if suitable merge it and assign me #1076  so that i can start work on tht too

**Comment by PriyaGhosal** [comment]
@snehhhcodes Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch.

**Comment by PriyaGhosal** [comment]
@snehhhcodes Are you working on it

**Comment by snehhhcodes** [comment]
> @snehhhcodes Are you working on it

yes m working on it

**Comment by snehhhcodes** [comment]
@PriyaGhosal can you check it now

**Comment by snehhhcodes** [comment]
@PriyaGhosal UPDATED!!

**Pull request closed without merging**
