### PR TITLE
Fix: #1171 - Fixed all links of navbar and footer throughout the project

### PR DESCRIPTION
**Pull request by Annapoornaaradhya**
# Related Issue #1171 

Also added changes in footer aswell as requested in #1256

Fixes:  #1171 

# Description

The navbar links are not working properly in all the subpages so fixed them for all the html files for the entire project where the links were no working.

 #1171 

# Type of PR

- [x] Bug fix

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

@PriyaGhosal Please assign this issue under hacktoberfest accecpted gssoc-ext level 3 tags

Thank you

### CODE REVIEW

**Comment by Annapoornaaradhya** [comment]
image
image
THERE ARE NO CONFLICTS THIS TIME

**Comment by PriyaGhosal** [comment]
@Annapoornaaradhya 
image
Please see the conflicts . Resolve the conflicts .

**Comment by Annapoornaaradhya** [comment]
Sure I will do it in another half an hour please don't close the PR

**Comment by Annapoornaaradhya** [comment]
image
I have resolved the conflicts now @PriyaGhosal

**Comment by PriyaGhosal** [comment]
In header 
Blog - Contact button
Fly contact button 
These are not working 
Please review footer and header again . 
image

**Comment by Annapoornaaradhya** [comment]
@PriyaGhosal please check it now I have checked them twice.
Thank you for your time.

**Comment by Annapoornaaradhya** [comment]
@samarth-6 @PriyaGhosal can you please review and merge this PR

**Comment by PriyaGhosal** [comment]
@Annapoornaaradhya Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile!
Great contribution ! 🎉

**Comment by Annapoornaaradhya** [comment]
Thank you @PriyaGhosal can you please make it level 3 as I have worked a lot on this

**Comment by PriyaGhosal** [comment]
@Annapoornaaradhya Sorry, level3 is given only if feature added or making a new webpage with details into it ... You can do one of those thing to get level3 ,there are still few days left

**Pull request merged**
