### PR TITLE
Enhanced Cookie policy section 

### PR DESCRIPTION
**Pull request by shivenyadavs**
# Related Issue

None

Fixes:  #1834 

# Description
Enhanced the Privacy Policy page UI to create a more professional, modern, and user-friendly experience. The changes improve readability, navigation, and overall aesthetic while maintaining accessibility standards.
Layout & Structure

Added a fixed header with logo and theme toggle
Implemented a two-column grid layout (300px sidebar + main content)
Created a sticky table of contents for easier navigation
Improved content hierarchy and section organization
Added proper spacing between elements using CSS Grid and Flexbox
Reorganized HTML structure using semantic elements

Added clear visual hierarchy for cookie information
Implemented expandable sections for detailed cookie descriptions
Created tooltips for technical terms
Added visual indicators for active/inactive cookies
Improved mobile responsiveness of cookie controls
Added inline code comments explaining cookie logic
Created user documentation for cookie management
Added developer documentation for cookie implementation
Updated privacy policy to reference cookie handling
Added change log for cookie policy versions
#1834

# Type of PR

- [X] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/cd8c0655-2f76-44e6-b66e-03eb60811f6f

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by shivenyadavs** [comment]
i have also included 2nd issue also #1836 
please check and do the needful

**Comment by shivenyadavs** [comment]
this PR is solving 2 issues

**Comment by shivenyadavs** [comment]
@PriyaGhosal please check the changes and merge it

**Comment by shivenyadavs** [comment]
@samarth-6  can you please check the changes and merge it

**Comment by PriyaGhosal** [comment]
@shivenyadavs 
Please see the conflicts .

**Comment by shivenyadavs** [comment]
done can you check

**Comment by shivenyadavs** [comment]
@PriyaGhosal please merge this pr

**Comment by shivenyadavs** [comment]
I have made the changes

**Comment by shivenyadavs** [comment]
now can u merge

**Comment by shivenyadavs** [comment]
@sanjay-kv @PriyaGhosal can you please merge

**Pull request merged**
