### PR TITLE
Enhanced Footer with Social Links ON README 

### PR DESCRIPTION
**Pull request by alo7lika**
# Related Issue

Fixes: #1525 

# Description
Enhanced the footer with social links in the README.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify):

# Screenshots / videos (if applicable)
Screenshot 2024-10-26 151956

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by alo7lika** [comment]
@PriyaGhosal  the task has been completed.

**Comment by PriyaGhosal** [comment]
@alo7lika 
image
Add all links here ...after thank you contact us doesn't look good

**Comment by alo7lika** [comment]
> @alo7lika image Add all links here ...after thank you contact us doesn't look good

okay let me modify it

**Comment by alo7lika** [comment]
Screenshot 2024-10-26 155819


done @PriyaGhosal

**Comment by PriyaGhosal** [comment]
@alo7lika  
Great contribution ! 🎉

**Pull request merged**
