### PR TITLE
ADD ROADMAP

### PR DESCRIPTION
**Pull request by alo7lika**
# Related Issue

Fixes: #1586 

# Description
The existing documentation may lack clarity in outlining the project's future features. To enhance it, specific details on planned updates, improvements, or new functionalities will be added, along with timelines for implementation. Deleting any vague statements or redundant information will streamline the section. Additionally, structuring the roadmap with bullet points or sections for each feature will improve readability and allow contributors to understand the project's direction easily. 

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

# Screenshots/videos (if applicable)
Screenshot 2024-10-26 171413

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by alo7lika** [comment]
@PriyaGhosal  kindly review the PR

**Comment by alo7lika** [comment]
> @PriyaGhosal kindly review the PR

@PriyaGhosal

**Comment by alo7lika** [comment]
@PriyaGhosal kindly review the PR

**Comment by alo7lika** [comment]
> @PriyaGhosal kindly review the PR

@PriyaGhosal

**Comment by alo7lika** [comment]
> @PriyaGhosal kindly review the PR

@PriyaGhosal

**Comment by alo7lika** [comment]
> @PriyaGhosal kindly review the PR

@PriyaGhosal

**Comment by PriyaGhosal** [comment]
@alo7lika Sorry but this is not required in readme

**Pull request closed without merging**
