### PR TITLE
Refactor Travel Itinerary Section

### PR DESCRIPTION
**Pull request by snehhhcodes**
# Fixes:  #1126 

# Description

### Issue Description:
The Travel Itinerary section previously featured three separate options: Family Vacation, Solo Adventure, and Romantic Getaway. Each option directed users to distinct pages to create itineraries, which created unnecessary navigation and complexity, making it less convenient for users who wanted to quickly create or access itineraries.

### Proposed Enhancements:
To address this issue, I propose implementing a centralized itinerary maker on the homepage. This enhancement would allow users to create their own itineraries for any type of trip without the need to navigate to separate pages. Additionally, the user interface will be simplified to enable easy entry of activities, locations, dates, and times, thus improving the overall accessibility of the itinerary creation process. By removing the need for multiple pages, users will benefit from a quicker and more efficient experience in planning their trips.

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[screen-capture.webm](https://github.com/user-attachments/assets/2f43d0a3-341d-4013-9d3c-96fd04c07be6)

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by snehhhcodes** [comment]
@PriyaGhosal Please review it once and add appropriate labels

Would be great if you can label it under level 3

**Comment by PriyaGhosal** [comment]
@snehhhcodes Please see the conflicts . Resolve the conflicts .

**Comment by snehhhcodes** [comment]
> @snehhhcodes Please see the conflicts . Resolve the conflicts .

solved!! please  check now @PriyaGhosal

**Comment by snehhhcodes** [comment]
> @snehhhcodes There is white border forming around website . Please remove it image

mam i tried to remove it tho the code seems okay as i checked the previous code too i have just synced the repo hence these chnges are made by someone else there are multiple changes now in css file even with the text color container for hotel and all everything has chnged so it is impossible to find things out now for me 

I tried removing the white border by inspecting it but the code is oke someone have chnged the whole structure hence now whole webpage's width is decreased!!
I am sorry I am unable to find the particular code to fix

**Comment by snehhhcodes** [comment]
would be great if you can merge my pr for my issue but on other hand m still finding the particular bug once found if i can make any change i will surely

**Comment by PriyaGhosal** [comment]
@snehhhcodes Please see the conflicts .

**Comment by snehhhcodes** [comment]
> @snehhhcodes Please see the conflicts .

solved

**Comment by snehhhcodes** [comment]
@PriyaGhosal mam it would be great if you can merge it as it been 2 days since m syncing the repo again n again so tht it wont cause any merge conflicts

**Comment by PriyaGhosal** [comment]
@snehhhcodes Sorry but Your code still have error due to which UI of page getting destroyed . Since a lot of changes happened in this PR I think creating new PR can solve it. 
image

**Comment by snehhhcodes** [comment]
> @snehhhcodes Sorry but Your code still have error due to which UI of page getting destroyed . Since a lot of changes happened in this PR I think creating new PR can solve it. 
> image
> 

surely thn i will create a new PR no issues

**Pull request closed without merging**
