### PR TITLE
Fixed misalignment issue ! #1034 #1036

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #1034 #1036

Fixed all these Issue in main page Footer &  Hotel booking page Header -

Screenshot 2024-10-19 124540
Screenshot 2024-10-19 124609

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________
# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile!
Great contribution ! 🎉

**Comment by Subhajit-2023-44** [comment]
> image
> 
> image @Subhajit-2023-44 Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review. Thank you!

@PriyaGhosal PA I didn't do anything here..  I just solved these two issues #1034 #1036 in header and footer..

Please merge my PR and add level 2

Thank You

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal level ??

**Pull request merged**
