### PR TITLE
Bug Fix: Chatbot not working properly 

### PR DESCRIPTION
**Pull request by yashksaini-coder**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #938 

# Description

I found out that the multiple if else statements were not proper, and was requesting large response from the user, that's why I stored every bit of info in the lists, that is easily mapped.

# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@PriyaGhosal can you review this PR, and add proper labels too.

**Comment by PriyaGhosal** [comment]
@yashksaini-coder 
image
Please see the conflicts highlighted in the image above.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder image Please see the conflicts highlighted in the image above.

I don't understand what's wrong here

**Comment by yashksaini-coder** [comment]
Hi I guess that chatbot has changed so this code is no longer required

image

**Pull request closed without merging**
