### PR TITLE
Second branch

### PR DESCRIPTION
**Pull request by sachinggsingh**
# Related Issue
Fixes:  #1966

# Description
Unnecessary left margin was given  which has been removed from it

# Screenshots / videos (if applicable)
**How it was**
Screenshot 2024-11-09 124029
**How it is**
Screenshot 2024-11-09 135104

### CODE REVIEW

**Comment by sachinggsingh** [comment]
@PriyaGhosal please merge my PR for #1968

**Comment by sachinggsingh** [comment]
@PriyaGhosal please merge my PR for https://github.com/PriyaGhosal/BuddyTrail/pull/1968

**Comment by PriyaGhosal** [comment]
Please see the conflicts . Resolve the conflicts .
@sachinggsingh

**Comment by sachinggsingh** [comment]
Resolved

**Comment by sachinggsingh** [comment]
> Please see the conflicts . Resolve the conflicts . @sachinggsingh

resolved

**Pull request merged**
