### PR TITLE
fixed the header issues  from  issue#350

### PR DESCRIPTION
**Pull request by Nimit1775**
# Related Issue

#350 

Fixes:  #(issue no.)

#350 

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

in this PR i have fixed the overlapping header  issue  , made a dropdown for the header  in smaller screens   , made the header responsive  , made the exclusive deals section responsive too 
fixes issue :- #350 

# Type of PR

- [x] Bug fix
- [x] Feature enhancement

# Screenshots / videos (if applicable)

https://drive.google.com/drive/folders/1oNAG6xFbXo2lVd_tymhkTYPzkI0jaiVK?usp=drive_link
( attached google drive link for screen shots  )  

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Nimit1775** [comment]
@PriyaGhosal  for the images  kindly check the  google drive link provided  
i have fixed the  issue #350

**Comment by Nimit1775** [comment]
@anuragverma108 @PriyaGhosal  can you please  add the correct labels in this PR for gssoc and hacktoberfest  so that it shows in the leaderboard  
thanks

**Comment by Nimit1775** [comment]
and also the gssoc-ext label @anuragverma108 @PriyaGhosal

**Comment by Nimit1775** [comment]
please add the labels for gssoc  @PriyaGhosal

**Comment by Nimit1775** [comment]
sir  please add the labels for gssoc-extd and hacktoberfest you forgot to
add them

**Comment by MastanSayyad** [comment]
@yashksaini-coder Why are your commits here in his PR?

image

**Comment by Nimit1775** [comment]
@MastanSayyad   his commits are also getting shown in PR #378  which is my PR

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder Why are your commits here in his PR?
> 
> image

Let me check this real quick @MastanSayyad

**Comment by yashksaini-coder** [comment]
@Nimit1775 I apologize I am fixing this bug right now.

**Comment by PriyaGhosal** [comment]
@MastanSayyad I was merging the PR and adding labels, but I might have missed something by mistake. Additionally, I was unable to add you as a collaborator because the GitHub ID given in email address was not accessible. I will add you shortly.

**Comment by PriyaGhosal** [comment]
@Nimit1775 Great Contribution in GSSOC-EXT 2024 🎉🎉🎉🎉

**Comment by yashksaini-coder** [comment]
can you check this ASAP https://github.com/PriyaGhosal/BuddyTrail/pull/406 its a bug fix

**Pull request merged**
