### PR TITLE
Add ratings 

### LINKED ISSUE #1570: Feat: Rate us implementation
### Describe the feature

Want to add the rate us implementation. SO that the users ratings and messages are stored in the database.

### Add ScreenShots

Screenshot 2024-10-26 153428

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue
 
## fixes #1570 

# Description

THIS PR created the necessary routes models and controllers in the backend of the project for submitting the users ratings for the website and also integrated with the frontend to make the call to the API.

issue #1570 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-10-27 153953
Screenshot 2024-10-27 154013

# Checklist:

- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@haseebzaki-07 
image
Even though I have given rating why does it shows this ... Please resolve this

**Comment by haseebzaki-07** [comment]
hey @PriyaGhosal please merge the PR for the backend part, I will fix the frontend

**Comment by PriyaGhosal** [comment]
@haseebzaki-07 
Please see the conflicts .

**Comment by haseebzaki-07** [comment]
hey @PriyaGhosal resolved the conflicts

**Comment by PriyaGhosal** [comment]
image
@haseebzaki-07 Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Comment by haseebzaki-07** [comment]
hey @PriyaGhosal please finalize this, I am getting merge conflicts.

**Comment by PriyaGhosal** [comment]
@haseebzaki-07 
Great contribution ! 🎉 Your pull request has been successfully merged! Also Take a moment to ⭐ Star the repository if you haven't already.

**Pull request merged**
