### PR TITLE
Modification of README.md file(Design), & Creation of dedicated Contributing.md file and LICENSE.

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Related Issue

- Fixes:  #311 

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

### 2) Modified the **Contributors section** [**Automated** the contributor addition].

**NOTE:** However, the looks have changed (video attached below for reference). **Please do not manually add Contributors anymore**. Focus that time of reviewing PRs and visiting the Issue sections incase any Contributor needs you.

## 2. Add a dedicated Contributing.md

Also added a redirect to **Contributing.md** from **README.md**

## 3. Added MIT LICENSE
Adding a LICENSE file is a best practice for open-source projects.

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

https://github.com/user-attachments/assets/6500aef2-501b-42b2-8929-6f54c8219660

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal Please review the PR and assign **level3** on the PR since I have updated and modified a lot of things, making your repository more accessible and readable. I have also automated the Contributors Mention section, further reducing your workload.

## **NOTE: This is again a reminder that please do not add Contributors manually anymore!**

**Comment by PriyaGhosal** [comment]
image
@rajdeepchakraborty-rc Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal Please reopen the PR
I can resolve the conflicts in this PR itself.

**Comment by rajdeepchakraborty-rc** [comment]
> @PriyaGhosal Please review the PR and assign **level3** on the PR since I have updated and modified a lot of things, making your repository more accessible and readable. I have also automated the Contributors Mention section, further reducing your workload.
> 
> ## **NOTE: This is again a reminder that please do not add Contributors manually anymore!**

@PriyaGhosal Also I have notified you multiple times that stop adding Contributors manually. Conflicts will keep arising otherwise.

**Comment by rajdeepchakraborty-rc** [comment]
I noticed that there is an automation file in your project that is creating the problem.

**Pull request closed without merging**
