### PR TITLE
Fixed the footer of About Us page

### PR DESCRIPTION
**Pull request by Annapoornaaradhya**
# Related Issue

#1854 

Fixes:  #1854 

# Description
BEFORE

Screenshot 2024-11-01 162830

AFTER
Screenshot 2024-11-01 165429

 #1854 

# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Checklist:

- [X] I have made this change from my own.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

@PriyaGhosal @samarth-6 please review the code and assign this under GSSOC-EXT and level

### CODE REVIEW

**Comment by Annapoornaaradhya** [comment]
@PriyaGhosal can you please review this and merge the PR

**Comment by PriyaGhosal** [comment]
@Annapoornaaradhya Please see the conflicts .

**Comment by Annapoornaaradhya** [comment]
@PriyaGhosal I have resolved the conflicts

**Comment by Annapoornaaradhya** [comment]
@PriyaGhosal can you please check this out an merge the PR because only 3 days are left

**Comment by Annapoornaaradhya** [comment]
> # Related Issue
> #1854
> 
> Fixes: #1854
> 
> # Description
> BEFORE
> 
> Screenshot 2024-11-01 162830
> 
> AFTER Screenshot 2024-11-01 165429
> 
> #1854
> # Type of PR
> * [x]  Bug fix
> * [ ]  Feature enhancement
> * [ ]  Documentation update
> * [ ]  Other (specify): _______________
> 
> # Checklist:
> * [x]  I have made this change from my own.
> * [x]  My code follows the style guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented my code, particularly in hard-to-understand areas.
> * [x]  I have made corresponding changes to the documentation.
> * [x]  My changes generate no new warnings.
> * [x]  I have tested the changes thoroughly before submitting this pull request.
> * [x]  I have provided relevant issue numbers and screenshots after making the changes.
> 
> @PriyaGhosal @samarth-6 please review the code and assign this under GSSOC-EXT and level

@PriyaGhosal please merge this

**Pull request merged**
