### PR TITLE
book now and explore more button functionable

### PR DESCRIPTION
**Pull request by INam1995**
Fixes: https://github.com/PriyaGhosal/BuddyTrail/issues/172
Fixes: https://github.com/PriyaGhosal/BuddyTrail/issues/171

Description
I have now made the 'Book Now' and 'Explore More' button functional, as it previously wasn’t working for every deal. I created a new webpage for each deal, as each one has different requirements. A reference video is provided below, showing the changes made.

Please make sure to add label 3 for both pr.

https://github.com/PriyaGhosal/BuddyTrail/issues/172 completed
https://github.com/PriyaGhosal/BuddyTrail/issues/171 completed

Type of PR
[ x] Feature enhancement

Screenshots / videos (if applicable)

Book now button is working (https://github.com/PriyaGhosal/BuddyTrail/issues/172 )

image

image

Explore More button is working(https://github.com/PriyaGhosal/BuddyTrail/issues/171 )

https://github.com/user-attachments/assets/736d5a1e-781d-418d-8b20-d94e65c896a5

Checklist:
[ x] I have made this change from my own.
[x ] My code follows the style guidelines of this project.
[ x] I have performed a self-review of my own code.
[ x] I have commented my code, particularly in hard-to-understand areas.
[ x] I have made corresponding changes to the documentation.
[ x] My changes generate no new warnings.
[ x] I have tested the changes thoroughly before submitting this pull request.
[ x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by INam1995** [comment]
@PriyaGhosal 
image
I have resolved all conflicts.

**Comment by PriyaGhosal** [comment]
@INam1995 Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch.
image

**Comment by INam1995** [comment]
image
done please let me know if there is any issue
@PriyaGhosal

**Comment by PriyaGhosal** [comment]
@INam1995 
This is not looking good. Remove it totally
image

you only add explore more section webpages . They are very nice 
image

**Comment by PriyaGhosal** [comment]
@INam1995 
this is not visible
image
leave Exclusive deals as it is 
image
Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
