### PR TITLE
Add a new ChatBot Assistant done ! #1246

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new Feature - #1246
Add a ChatBot Assistant done✅ (💬I add a new ChatBot Assistant because the existing ChatBot Assistant is not working)

🔴Before -

https://github.com/user-attachments/assets/5ac8a44f-0e47-4fcf-ac4a-f9faa9bcbc0a

🟢After - 

https://github.com/user-attachments/assets/cc7f0c4c-d87a-40a9-a3e2-93ff34c37bc9

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________
# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal merge my PR and add level 3, you can check my code & videos...

Thank You

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 
image
Please see the conflicts . Resolve the conflicts .

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 image
> 
> Please see the conflicts . Resolve the conflicts .

wait i will give new PR

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal Done

**Pull request closed without merging**
