### PR TITLE
Modification of README.md file(Design), & Creation of dedicated Contributing.md file and LICENSE.

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Related Issue

- Fixes:  #311 

# Description

### 2) Modified the **Contributors section** [**Automated** the contributor addition].

**NOTE:** However, the looks have changed (video attached below for reference). **Please do not manually add Contributors anymore**. Focus that time of reviewing PRs and visiting the Issue sections incase any Contributor needs you.

## 2. Add a dedicated Contributing.md

Also added a redirect to **Contributing.md** from **README.md**

## 3. Added MIT LICENSE
Adding a LICENSE file is a best practice for open-source projects.

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/d28814f2-399a-4236-8ca2-485a5fa8ab96

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal Please review the PR and please assign **level2** on the PR since I have updated and modified a lot of things, making your repository more accessible and readable.

**Comment by rajdeepchakraborty-rc** [comment]
# Please read this message!
Incase you face a merge conflict by the time you review this PR, **do not** close this PR! 
There is a very high chance of having a conflict. Just let me know and wait a bit. I will resolve it in this PR itself and please merge it henceforth.

**Comment by PriyaGhosal** [comment]
@rajdeepchakraborty-rc Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile!
Great contribution to GSSOC'24 EXTENDED! 🎉

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal Thanks for reviewing the PR.

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal Please update the level on the issue #311

**Pull request merged**
