### PR TITLE
Update UI of Exclusive Deals section

### PR DESCRIPTION
**Pull request by Jetshree**
# Related Issue

None

Fixes: #1419   

# Description

This PR fixes the issue #1419  by changing theme of Exclusive Deals section.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [x] CODE CHANGE

# Screenshots / videos (if applicable)
Before:
Screenshot 2024-10-23 202228

After:
Screenshot 2024-10-24 014145

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Jetshree** [comment]
@PriyaGhosal please guide me on how to fix PR Description Check

**Comment by PriyaGhosal** [comment]
@Jetshree Please see the conflicts . Resolve the conflicts .

**Comment by PriyaGhosal** [comment]
@Jetshree Please see the conflicts .

**Comment by Jetshree** [comment]
@PriyaGhosal  I have solved the conflicts and created a new pr. Please check pr #1557

**Pull request closed without merging**
