### PR TITLE
created advanced search and filtering option

### PR DESCRIPTION
**Pull request by Uruz-fazar**
# Related Issue

[“None”]

Fixes issue: #1165 

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]

#1165 

# Type of PR

- [x] Feature enhancement
- [x] Documentation update

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [  ] I have made this change from my own.
- [  ] My code follows the style guidelines of this project.
- [  ] I have performed a self-review of my own code.
- [  ] I have made corresponding changes to the documentation.
- [  ] My changes generate no new warnings.
- [  ] I have tested the changes thoroughly before submitting this pull request.
- [  
WhatsApp Image 2024-10-22 at 10 46 12 PM
] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Uruz-fazar** [comment]
#1165 @PriyaGhosal please review and merge it in level 2.

**Comment by PriyaGhosal** [comment]
@Uruz-fazar 
image
No advanced option is showing in your preview. Resolve it

**Comment by Uruz-fazar** [comment]
resolved the issue @PriyaGhosal

**Comment by PriyaGhosal** [comment]
@Uruz-fazar 
image
Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
