### PR TITLE
Cookie policy, Contribution page, footer section

### PR DESCRIPTION
**Pull request by Pushpa472**
@PriyaGhosal 
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #(issue no.)

# Description
I have made several improvements to the website, including:
1. Added a header and footer to various pages, ensuring consistent design.
2. Enhanced the cookie policy, copyright, terms of service, privacy policy, and disclaimer pages.
3. Improved the footer alignment on other pages for better consistency.
4. Updated the About, FAQ, and Team pages, and added margin-bottom spacing to the Contact page.
5. Fixed alignment issues in the footer section of the Contributor page.
6. Resolved a bug in the header section of the Contributor page, where the navigation was displaying the default user agent stylesheet instead of the applied CSS.
7. Integrated Google Translator on several pages to improve accessibility.

 issue no. #1422

# Type of PR

- [x ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
before: Cookie_policy page
image
after
image

before: contributor page 
image
after
image

before: FAQ  page
image
after
Screenshot 2024-10-30 145329

before: Copyright page
Screenshot 2024-10-27 170756
after
image

# Checklist:

- [ x] I have made this change from my own.
- [ x] I have taken help from some online resources.
- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Pushpa472** [comment]
@PriyaGhosal If there is any issue in code plz let me known

**Comment by PriyaGhosal** [comment]
@Pushpa472 
Please see the conflicts .

**Comment by Pushpa472** [comment]
@PriyaGhosal Hmm, I'm solving the conflict.

**Comment by PriyaGhosal** [comment]
@Pushpa472 Are you working on it or should I close it

**Comment by Pushpa472** [comment]
@PriyaGhosal I already resolve conflict, i don't know why happing this ... two times i resolve conflict and show there is no conflict in this branch

**Comment by Pushpa472** [comment]
image

**Comment by Pushpa472** [comment]
@PriyaGhosal I solve the conflict please review  it

**Comment by PriyaGhosal** [comment]
@Pushpa472 Please see the conflicts .

**Comment by Pushpa472** [comment]
@PriyaGhosal now check it

**Comment by PriyaGhosal** [comment]
image
please resolve

**Comment by Pushpa472** [comment]
@PriyaGhosal how I can resolve not show me any conflict ...plz tell me

**Pull request closed without merging**
