### PR TITLE
Removed the unwanted image

### PR DESCRIPTION
**Pull request by Sudhanshu248**
# Related Issue

BUG: REMOVE THIS PICTURE #679 , , Removed the image #692 , Removed the unwanted Image #773 , Removed the Image #787

Fixes:  #(issue no. #679 

# Description

The image is not fixed properly, I've removed the image that enhances the website's looks.

Issue no: #679 

# Type of PR

- [ ] Bug fix

# Screenshots / videos (if applicable)
Before:
Screenshot 2024-10-15 205542

After:
Screenshot 2024-10-15 205617

# Checklist:

- [x ] I have made this change from my own.
- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] My changes generate no new warnings.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Sudhanshu248** [comment]
@PriyaGhosal @samarth-6    Please review my pr and also add label of gssoc-ext, hactoberfest'24, hacktoberfest-accepted, level-2/3.

**Comment by Sudhanshu248** [comment]
Give some time to resolve the conflict

**Comment by PriyaGhosal** [comment]
@Sudhanshu248 Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile!
Great contribution ! 🎉

**Comment by Sudhanshu248** [comment]
@PriyaGhosal Can you please level up ( 1 to 2/3).

For this issue. As it is a big issue or bug. Due to which whole website will effect

**Pull request merged**
