### PR TITLE
fixed the scroll up button,enhanced the colors indark mode and divs aligned

### PR DESCRIPTION
**Pull request by Shobhit1729Aryan**
BEFORE
[BEFORE22.zip](https://github.com/user-attachments/files/17401335/BEFORE22.zip)
AFTER
[AFTER22.zip](https://github.com/user-attachments/files/17401339/AFTER22.zip)

### CODE REVIEW

**Comment by Shobhit1729Aryan** [comment]
@PriyaGhosal  Good evening mam ,would you please consider in increasing the level ...

**Comment by PriyaGhosal** [comment]
@Shobhit1729Aryan Can you make all button sky in dark mode and leave logo colour as it is i.e White which is according to the theme 
image
This sky colour

**Comment by PriyaGhosal** [comment]
@Shobhit1729Aryan Are you working on it??

**Comment by Shobhit1729Aryan** [comment]
> @Shobhit1729Aryan Are you working on it??

Yes ,I will update till evening today

**Comment by anuragverma108** [comment]
Conflicting files
about.html
chatbot.css

Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
