### PR TITLE
Modified carousel to display proper tiles

### PR DESCRIPTION
**Pull request by shreya2k3**
# Related Issue

Modified the carousel on the home page to show the correct number of tiles.

Fixes:  #1491 

# Description

Earlier uneven number of carousel was shown , but now within each slider only 3 carousel tiles are shown.

# Type of PR

- [x] Bug fix

# Screenshots / videos (if applicable)
**Before Change**
image

**After Change**
image

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by shreya2k3** [comment]
@PriyaGhosal Please merge my PR

**Comment by PriyaGhosal** [comment]
@shreya2k3 Please see the conflicts .

**Comment by shreya2k3** [comment]
@PriyaGhosal I have Resolved the conflicts

**Comment by PriyaGhosal** [comment]
@shreya2k3 There are still some conflicts .Please resolve them

**Pull request closed without merging**
