### PR TITLE
fixed whole footer part of blog page 

### PR DESCRIPTION
**Pull request by AsifQamar**
@PriyaGhosal @samarth-6 please review and merge it in repective level

before
Screenshot_487

after
Screenshot_488

### CODE REVIEW

**Comment by AsifQamar** [comment]
@PriyaGhosal please review it

**Comment by MastanSayyad** [comment]
@AsifQamar ISSue link or number pls

**Comment by AsifQamar** [comment]
> @AsifQamar ISSue link or number pls

https://github.com/PriyaGhosal/BuddyTrail/issues/1971 @MastanSayyad

**Comment by AsifQamar** [comment]
@MastanSayyad its a auto assign thats why level 1 showing - we can give it in higer level

**Comment by MastanSayyad** [comment]
@AsifQamar given

**Comment by AsifQamar** [comment]
> @AsifQamar given
thanks

**Pull request merged**
