### PR TITLE
Issue #827 Solved :- Added Registration Pop up 

### PR DESCRIPTION
**Pull request by PrAyAg9**
# Related Issue
None

Fixes:  #827 

# Description
- A pop up is added on the landing page which will provoke users to register via exciting offer
- Clicking on no thanks or anywhere outside body will close the pop up 

# Type of PR

- [ ] Bug fix
- [yes ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
1) This is how it will look like:-
image

I did have more design, i shared it on issue description #827 

# Checklist:

- [yes ] I have made this change from my own.
- [ yes] My code follows the style guidelines of this project.
- [ yes] I have performed a self-review of my own code.
- [ yes] I have commented my code, particularly in hard-to-understand areas.
- [yes ] I have made corresponding changes to the documentation.
- [yes ] My changes generate no new warnings.
- [ yes] I have tested the changes thoroughly before submitting this pull request.
- [ yes] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by PrAyAg9** [comment]
@PriyaGhosal  I've attached the current look of pop up here as you can see up in description.

Other design is attached on the issue page you can also see that 
**Could you raise this issue from level 1 category as this requires a lot of time** 
    - I hope you like it, Thank you.

**Comment by PrAyAg9** [comment]
@samarth-6 Please review and approve it?

**Comment by PriyaGhosal** [comment]
@PrAyAg9 You have done great contribution but "No thanks" button is not working when I am checking it in preview. Please look into it . If it doesn't work you can put right corner cross symbol.

**Comment by PrAyAg9** [comment]
@PriyaGhosal Could you please check if it is working now?

**Comment by PriyaGhosal** [comment]
@PrAyAg9 
Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile!
Great contribution ! 🎉

**Pull request merged**
