### PR TITLE
feat: added scroll to top feature on about page

### PR DESCRIPTION
**Pull request by Palmistry2310**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #1717

# Description

added scroll to top feature

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
image

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

@PriyaGhosal please reveiw this pr

### CODE REVIEW

**Comment by Palmistry2310** [comment]
@PriyaGhosal please review this pr!

**Comment by PriyaGhosal** [comment]
@Palmistry2310 Please see the conflicts .

**Comment by PriyaGhosal** [comment]
Are you working on it or should I close it

**Comment by Palmistry2310** [comment]
@PriyaGhosal i have resolved the conflicts. 
also please add labels here.
pr #1430 has been merged but labels are not added please see to it once!

**Comment by PriyaGhosal** [comment]
@Palmistry2310 label given for #1430 ...........Project Mentor missed it

**Pull request merged**
