### PR TITLE
updated the social media icons with animations

### PR DESCRIPTION
**Pull request by ritikm31**
social media icon updated with animation

Fixes:  #1944 

# Description

social media icon updated with animation

# Type of PR
-  Feature enhancement

- I have made this change from my own.
-  I have taken help from some online resources.
- My code follows the style guidelines of this project.
- I have performed a self-review of my own code.
-  I have commented my code, particularly in hard-to-understand areas.
-  I have made corresponding changes to the documentation.
-  My changes generate no new warnings.
-  I have tested the changes thoroughly before submitting this pull request.
-  I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by ritikm31** [comment]
hope you like my contribution 
do a merge if you like it 
happy to contribute in it.

**Comment by ritikm31** [comment]
also added the blog in the blog section

**Comment by ritikm31** [comment]
#1946  completed

**Comment by PriyaGhosal** [comment]
@ritikm31 Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch. After resolving the conflicts, please open a new PR for review.
Thank you!

**Pull request closed without merging**
