### PR TITLE
solved #1337 added booking page resolved conflicts

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
# Related Issue

Fixes:  #1337 
please add level3 if possible

Uploading Untitled video - Made with Clipchamp (2).mp4…
# Description
Added  hotel booking 

# Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@KapuluruBhuvaneswariVspdbct 
image
Please see the conflicts .

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
mam please check once

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
mam please check

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@PriyaGhosal mam can you please review it once

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@PriyaGhosal  where should i add the hotel ,map  mam

**Pull request closed without merging**
