### PR TITLE
Add a new contributors page done ! #1494 ✅

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add Contributors page - #1494

Done(It display all Contributors and total Contributions properly) -

https://github.com/user-attachments/assets/e832f63b-3cb5-48e6-9bc8-3d3f6eed01d4

Before - #1494

# Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________
# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal merge my PR and add level 3, you can check my code & videos

Thank You

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44  Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile! Also Take a moment to ⭐ Star the repository if you haven't already.
Great contribution ! 🎉

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile! Also Take a moment to ⭐ Star the repository if you haven't already. Great contribution ! 🎉

Thank You 🙏🏻 but Level ??

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 Can You see contributors list or preloader is showing 
image

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Can You see contributors list or preloader is showing image

what ??

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 Is contributor list visible ? Can you send me SS of buddytrail website

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Is contributor list visible ? Can you send me SS of buddytrail website

wait i will send a video

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Is contributor list visible ? Can you send me SS of buddytrail website

@PriyaGhosal 



https://github.com/user-attachments/assets/d68a7d5d-dcb4-4285-be30-947f9055f44d

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 ig this is not Buddytrail main website because visitor count is around 66 . https://buddytrail.netlify.app/   please send ss of this website

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 ig this is not Buddytrail main website because visitor count is around 66 . https://buddytrail.netlify.app/ please send ss of this website .... My Internet is also working ,if anything doesn't work I would revert it and you need a make a fresh new pr

Ooo main website .. wait

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Did you see?? shall I close PR ... You can open a new PR as this PR may have conflicts

wait give me more 10 min

**Comment by Subhajit-2023-44** [comment]
I have nothing to do here.. Please check

**Comment by Subhajit-2023-44** [comment]
@PriyaGhosal

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 Ok I will check asap

**Comment by PriyaGhosal** [comment]
@Subhajit-2023-44 Sorry for delay but nothing was working so I needed to revert this pr .. Please create a new PR for review

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Sorry for delay but nothing was working so I needed to revert this pr .. Please create a new PR for review

okay 😔😔

**Pull request merged**
