### PR TITLE
added backend in feedback form

### PR DESCRIPTION
**Pull request by AyushSharma72**
i added backend  functionality so that user feedback can be saved in the database issue #1713

Screenshot (34)

database:
Screenshot 2024-10-28 204402

please add gssoc-ext and level3 before merge @PriyaGhosal

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@AyushSharma72 Please see the conflicts . 
image

**Comment by AyushSharma72** [comment]
> @AyushSharma72 Please see the conflicts . image

I have tested it it is working fine 
It is deployed on netlify so it could be cors error 
On your back-end only the localhost is allowed to send request you have to add the netlify url there then it will work

**Comment by AyushSharma72** [comment]
> @AyushSharma72 Please see the conflicts . image

the error is that on the frontend you have to add the url where your backend is hosted 
then it will work 
image
i have tested it :
image
on this fetch function you have to add the url of the backend
you can merge this pr @PriyaGhosal

**Comment by AyushSharma72** [comment]
hey @PriyaGhosal do you understand if not tell me and give me url of your hosted backend 
otherwise please merge this PR

**Comment by PriyaGhosal** [comment]
@AyushSharma72 
Great contribution ! 🎉 Your pull request has been successfully merged! Also Take a moment to ⭐ Star the repository if you haven't already.

**Pull request merged**
