### PR TITLE
solved #1339

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
# Related Issue
Added map for famous places in india
Fixes:  #1339

# Description

Added map for famous places in india

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
please consider it as level3
Uploading budytrail.mp4…

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
please considerit as level3

**Comment by PriyaGhosal** [comment]
@KapuluruBhuvaneswariVspdbct Add famous places in this map only as it is already there in website 
image
 After resolving the conflicts, please open a new PR for review.
Thank you!

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok

**Pull request closed without merging**
