### PR TITLE
Added preloader

### PR DESCRIPTION
**Pull request by Peart-Guy**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”] None

Fixes:  #1195

# Description

I added a custom preloader to the webapp

#1195

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/92c24c17-f5fd-4d23-94bb-41d5e6227797

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Peart-Guy** [comment]
@PriyaGhosal  
I have done my work kindly check it out
and give the GSSOC-24 EXTD, Hacktoberfest, and Level. It will be an honor

**Comment by PriyaGhosal** [comment]
@Peart-Guy Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch.

**Comment by Peart-Guy** [comment]
> @Peart-Guy Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch.


@PriyaGhosal  It is showing some issue related to my PR description. Can you please help me in this.

**Comment by Peart-Guy** [comment]
> @Peart-Guy Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files. Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch.


@PriyaGhosal 
I have resolved all the conflicts highlighted. Kindly check it out.

**Comment by PriyaGhosal** [comment]
@Peart-Guy can you remove the preloader coming after the pop up as it is very time taking

**Comment by PriyaGhosal** [comment]
@Peart-Guy Are you working on it

**Comment by Peart-Guy** [comment]
> @Peart-Guy Are you working on it

Ya i am working on it

**Comment by Peart-Guy** [comment]
> @Peart-Guy can you remove the preloader coming after the pop up as it is very irritating for user . only at the beginnig it is good and after clicking on no thanks in pop up preloader is not needed


@PriyaGhosal  I have tried several ways but couldn't figure it out

**Comment by PriyaGhosal** [comment]
@Peart-Guy Did you get anyway to solve the problem ? 
or Shall I close the issue

**Comment by Peart-Guy** [comment]
> @Peart-Guy Did you get anyway to solve the problem ? or Shall I close the pr

@PriyaGhosal  The preloader  automatically gets removed when the page is loaded fully. It does not depend on pop up.

**Comment by PriyaGhosal** [comment]
@Peart-Guy  Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile! Also Take a moment to ⭐ Star the repository if you haven't already.
Great contribution ! 🎉

**Pull request merged**
