### PR TITLE
BUG:Misaligned Icons in Travel Discussion Forum #1067

### LINKED ISSUE #1067: BUG:Misaligned Icons in Travel Discussion Forum
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue: Misaligned Icons in Travel Discussion Forum

**Description:**

In the Travel Discussion Forum, the icons for interactions such as replying, liking, sharing, and other actions are not well structured. This misalignment makes the layout appear inconsistent and unorganized, which negatively impacts the overall user experience. Properly aligning these icons is necessary to enhance visual clarity and usability.

---

**Steps to Reproduce:**
1. Navigate to the Travel Discussion Forum.
2. View the interaction icons (e.g., reply, like, share, etc.) in the posts or comments.
3. Observe that the icons are misaligned, which disrupts the clean layout of the forum.

---

**Expected Behavior:**
The interaction icons should be evenly spaced and aligned properly with the content, ensuring a visually consistent and professional-looking interface.

---

**Actual Behavior:**
Currently, the icons are not aligned properly, resulting in a cluttered and uneven layout that diminishes the user experience.

---

**Priority:** Medium

**Impact:** This affects user navigation and interaction within the Travel Discussion Forum, potentially causing confusion or frustration.

---

**Screenshots/Visuals:** 
Screenshot 2024-10-19 at 16 36 06

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by amanreddy77**
Expected Behavior:
The interaction icons should be evenly spaced and aligned properly with the content, ensuring a visually consistent and professional-looking interface.
Fixes #1067 
Actual Behavior:
Currently, the icons are not aligned properly, resulting in a cluttered and uneven layout that diminishes the user experience.

# Related Issue
None

# Description

**Description:**
This pull request addresses the misalignment and hover effects of the navigation icons within the travel discussion forum. The previous implementation did not provide a cohesive user experience when hovering over the navigation items, as the icon color only changed when the icon itself was hovered over, rather than the entire section.

**Changes Made:**
- Updated the CSS for the navigation items to ensure the icon color changes when hovering over the entire link (including both the text and icon).
- Introduced a flexbox layout for navigation links to better align icons and text, enhancing the overall visual appeal.
- Applied transition effects for smooth color changes and scaling of the icons upon hovering.

# Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/baf8949a-e8fb-4a1b-844b-368622ace95e

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@amanreddy77 Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch.

**Comment by amanreddy77** [comment]
> @amanreddy77 Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch.

yeah I am sry about that I have resolved the conflicts you can merge now

**Comment by PriyaGhosal** [comment]
@amanreddy77 Its still showing conflicts

**Comment by amanreddy77** [comment]
> @amanreddy77 Its still showing conflicts

can you check now please

**Pull request closed without merging**
