### PR TITLE
Added copyright page

### PR DESCRIPTION
**Pull request by Palmistry2310**
# Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #1072 

# Description
created and added a responsive copyright page.

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

https://github.com/user-attachments/assets/441a0b7d-4796-460e-b271-41a57f96fbcf

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

@PriyaGhosal please review this pr. And also assign this pr to me with the necessary labels.

### CODE REVIEW

**Comment by Palmistry2310** [comment]
@PriyaGhosal please review this pr.

**Comment by Palmistry2310** [comment]
@samarth-6 i have resolved the conflicts now, please review it now. And if you find it worth merging do add necessary labels.

**Comment by PriyaGhosal** [comment]
@Palmistry2310 Please see the conflicts . Resolve the conflicts . Ensure you pull all the latest changes before pushing your feature/bug fixes to the main branch.

**Comment by Palmistry2310** [comment]
@PriyaGhosal conflicts are resolved.

**Comment by PriyaGhosal** [comment]
@Palmistry2310 Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile!
Great contribution ! 🎉

**Pull request merged**
