### PR TITLE
Fix issue #1465 Add icons in Get in Touch Section.

### PR DESCRIPTION
**Pull request by Adityadhiman0**
# Related Issue
None
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

Fixes:  #1465

# Description

[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]
I fix issue no. #1465 And this pr will add icons in form in "get in touch" section

# Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
Before
Screenshot 2024-10-24 230833
After
Screenshot 2024-10-26 194240
Screenshot 2024-10-26 194250

# Checklist:

- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by Adityadhiman0** [comment]
I fix all conflicts which come in previous pr.
Now please merge this pr under hacktoberfest.

**Comment by Adityadhiman0** [comment]
Please review.

**Comment by Adityadhiman0** [comment]
Please review my pr.

**Comment by PriyaGhosal** [comment]
@Adityadhiman0 
image
NO ICON VISIBLE IN PREVIEW .

**Comment by Adityadhiman0** [comment]
I think I should refork this project's repo.
If I delete my fork then this pr will close automatically. 
I want to know, Is there any problem if I recreate my pr with new fork?

**Comment by PriyaGhosal** [comment]
@Adityadhiman0 
image
I think you forked without doing sync fork .... in this website preview no thanks button in pop up is not working

**Comment by PriyaGhosal** [comment]
@Adityadhiman0 Please resolve the conflicts

**Comment by Adityadhiman0** [comment]
I will resolve conflicts very soo

**Comment by Adityadhiman0** [comment]
Can I create a new pr and close this one. Because things are getting worse. I need to work on this from scratch. This will not take long time. Can i do that?

**Pull request closed without merging**
