### PR TITLE
created testimonials

### PR DESCRIPTION
**Pull request by 1ShahidBashir**
# Related Issue
#152 
🌟 Lacking Testimonial page

Fixes:  none

# Description

Added testimonials as a separate page

# Type of PR

- [ ] Bug fix
- [x ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
image

# Checklist:

- [x ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x ] My changes generate no new warnings.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by 1ShahidBashir** [comment]
@PriyaGhosal  Please check out this PR

**Comment by PriyaGhosal** [comment]
@1ShahidBashir From which button I can see this testimonial .... Did you linked it with main page

**Comment by 1ShahidBashir** [comment]
@PriyaGhosal it can create conflicts if I create button in index.html

**Comment by 1ShahidBashir** [comment]
@PriyaGhosal Please check the pr

**Comment by PriyaGhosal** [comment]
@1ShahidBashir 
image
This is totally outdated website . Please tell me your changes in our new website as many contribution have been done there after.
image
This above is the new one .... can you now point where you will add testimonials

**Comment by 1ShahidBashir** [comment]
here
image

**Comment by 1ShahidBashir** [comment]
@PriyaGhosal check it now

**Comment by PriyaGhosal** [comment]
@1ShahidBashir Please see the conflicts highlighted in the image above. Resolve the conflicts in the mentioned files.
image

**Comment by 1ShahidBashir** [comment]
@PriyaGhosal please check the PR now

**Comment by 1ShahidBashir** [comment]
@PriyaGhosal the conflicts are resolved please look to the PR now!!

**Comment by 1ShahidBashir** [comment]
@PriyaGhosal If I edit the index.html there will be merge conflicts, please ask a person with write access to create a button for testimonial.html

**Comment by PriyaGhosal** [comment]
@1ShahidBashir just add testimonial below rate your experience ... no need to add any button in header

**Comment by 1ShahidBashir** [comment]
@PriyaGhosal  please check it out now
image

**Comment by 1ShahidBashir** [comment]
@PriyaGhosal the conflicts are due to changes in index.html (main page) once merged there will be no errors

**Pull request closed without merging**
