### PR TITLE
Implemented an Emergency SOS Feature

### PR DESCRIPTION
**Pull request by avisha191**
# Related Issue

 “None”

Fixes:  #(issue no.)

# Description
How It Works:
Geolocation API: When the user clicks the SOS button, the app tries to get their location using the Geolocation API. This works only if the user grants permission to share their location.
Sharing Options: After getting the location, the user can choose to send an email or SMS with their current location to their emergency contacts. The JavaScript code generates a pre-written message with the location embedded.

#814 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]
Screenshot (416)
Please assign under level 2

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by PriyaGhosal** [comment]
@avisha191 What is the use of it in our website ... can you tell me its pros

**Comment by PriyaGhosal** [comment]
@avisha191 Reply

**Comment by avisha191** [comment]
1. Enhanced user safety: Users can quickly alert contacts or emergency
services in dangerous situations.
2. ncreased trust and reliability: Travelers feel more secure using a
platform that prioritizes safety.
3. Competitive advantage: Offering an SOS feature sets the platform apart
from competitors.
4. Real-time emergency response: Integration with location sharing allows
for faster assistance.
5. Compliance with safety regulations: Meets regional safety standards for
travel platforms.
6. Positive brand image: Boosts reputation, attracting more users through
safety-focused features.

**Comment by PriyaGhosal** [comment]
@avisha191 Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile!
Great contribution ! 🎉

**Pull request merged**
