### PR TITLE
F&Q page required #1118

### PR DESCRIPTION
**Pull request by isimarjitsingh**
Fixes:  #(1188)

# Description

so basically i just made a "F&Q PAGE" which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .

AS I ADDED:-
- add "F&Q" for directly navigation
- add relevant photo
- design the  whole section
- provide eye catching colors
- GIVE 3 SECTIONS
  1. about our website
  2. most frequent questions
  3. form for user collecting user personal questions
- ADD HOVER EFFECTS
- ADD TRANSITIONS
- BUIKD A interactive user interface
- and many more you need to check it out

F&Q page required #1118

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

--BEFORE:-
"NOTHING"

---AFTER:-
Screenshot 2024-10-19 223602
Screenshot 2024-10-19 223625

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by isimarjitsingh** [comment]
KINDLY MERGE MY PR AND LET ME KNOW IF THERE IS ANY ISSUE

**Comment by PriyaGhosal** [comment]
@isimarjitsingh Change F&Q TO FAQ

**Comment by isimarjitsingh** [comment]
DONE 👍

**Comment by PriyaGhosal** [comment]
@isimarjitsingh 
Your pull request has been successfully merged! Don't stop here—continue contributing by addressing more issues and aiming to become a top contributor. Exclusive swag awaits for those who go the extra mile!
Great contribution ! 🎉

**Pull request merged**
