### PR TITLE
Add subscribe

### LINKED ISSUE #1846: Feat: Subscribe us
### Describe the feature

Users filling in their mail ids in the mail id form should receive a confirmation message to their valid mail ids.

### Add ScreenShots

Screenshot 2024-11-01 115759

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by haseebzaki-07**
# Related Issue

## fixes #1846 

# Description

This PR adds the backend implementation for subscribe us also the frontend codes for calling the API.
Backend is working file, just a bug in the frontend the "email" field in not populating.

issue #1846 

# Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
Screenshot 2024-11-01 130113
WhatsApp Image 2024-11-01 at 1 13 01 PM (1)

# Checklist:

- [X] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by haseebzaki-07** [comment]
hey @PriyaGhosal please check this PR

**Comment by haseebzaki-07** [comment]
@PriyaGhosal please check this pR

**Comment by PriyaGhosal** [comment]
Please see the conflicts .

**Comment by haseebzaki-07** [comment]
@PriyaGhosal resolved the conflicts

**Pull request merged**
