### PR TITLE
Enhanced the ui of footer

### PR DESCRIPTION
**Pull request by shalomrionafernandes**
# Related Issue
Fixes:  #1282

# Description
Enhanced the UI of footer to look more professional and be responsive

BEFORE:
image

AFTER:
image

# Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.]

# Checklist:

- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by shalomrionafernandes** [comment]
@PriyaGhosal I have done the required changes, pls look into it. Thank you!

**Comment by PriyaGhosal** [comment]
@shalomrionafernandes Please see the conflicts .

**Comment by PriyaGhosal** [comment]
Are you working on it or should I close it

**Comment by shalomrionafernandes** [comment]
I am working on it, will update you by tonight if I'm unable to proceed

**Comment by shalomrionafernandes** [comment]
@PriyaGhosal I have resolved the conflicts, pls check now

**Comment by PriyaGhosal** [comment]
@shalomrionafernandes Great contribution ! 🎉 Your pull request has been successfully merged! Also Take a moment to ⭐ Star the repository if you haven't already.

**Pull request merged**
