### PR TITLE
✨Added a localStorage and refactored CSS ✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
- Added a local storage which will store the user inputs.
- fixed the CSS UI.
- solved(Issue #79)

@PriyaGhosal please review this and tag level aswell.

https://github.com/user-attachments/assets/bcd5a618-eb08-4e14-8462-95fbb089db81

Screenshot 2024-10-06 at 12 31 10 AM

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@PriyaGhosal since ive added localstorage aswell will this be level3?

**Comment by T-Rahul-prabhu-38** [comment]
@PriyaGhosal can you please review this , thank you :)

**Comment by T-Rahul-prabhu-38** [comment]
@PriyaGhosal  can you please review this PR , it will be very helpful.
Thank you!

**Comment by T-Rahul-prabhu-38** [comment]
@PriyaGhosal  Can you please review this , it will be really helpful.
Thank you!

**Comment by T-Rahul-prabhu-38** [comment]
@PriyaGhosal i had made this PR 2 days ago can you please review this, it will be of great help

**Comment by T-Rahul-prabhu-38** [comment]
@can you add the levels as well please

**Comment by PriyaGhosal** [comment]
@T-Rahul-prabhu-38 There was already book a cab auto form please open a new PR for review.
Thank you!

**Comment by T-Rahul-prabhu-38** [comment]
no im asking abt assigning the level to this merged PR.
only then it will reflect on the leaderboard.

**Comment by T-Rahul-prabhu-38** [comment]
> @T-Rahul-prabhu-38 There was already book a cab auto form please open a new PR for review. Thank you!

im a little confused right now , do u want me to create a PR with the same code ?

**Pull request merged**
